In [2]:
import torch

In [3]:
B = 3
D = 4
M = torch.rand((B, D, D))

In [4]:
print(M)

tensor([[[0.8359, 0.8453, 0.4773, 0.9922],
         [0.5976, 0.5614, 0.2343, 0.8495],
         [0.9159, 0.2730, 0.5825, 0.6727],
         [0.4473, 0.0311, 0.4938, 0.4559]],

        [[0.2886, 0.6005, 0.5938, 0.5624],
         [0.3884, 0.9211, 0.3994, 0.8212],
         [0.5156, 0.5738, 0.2689, 0.0422],
         [0.2412, 0.7686, 0.3943, 0.1545]],

        [[0.9434, 0.3097, 0.0745, 0.0143],
         [0.1518, 0.7089, 0.1221, 0.5434],
         [0.9328, 0.2329, 0.3813, 0.3170],
         [0.6582, 0.1510, 0.6540, 0.3969]]])


In [6]:
I = torch.eye(D)
print(I)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [7]:
print(M - I)

tensor([[[-0.1641,  0.8453,  0.4773,  0.9922],
         [ 0.5976, -0.4386,  0.2343,  0.8495],
         [ 0.9159,  0.2730, -0.4175,  0.6727],
         [ 0.4473,  0.0311,  0.4938, -0.5441]],

        [[-0.7114,  0.6005,  0.5938,  0.5624],
         [ 0.3884, -0.0789,  0.3994,  0.8212],
         [ 0.5156,  0.5738, -0.7311,  0.0422],
         [ 0.2412,  0.7686,  0.3943, -0.8455]],

        [[-0.0566,  0.3097,  0.0745,  0.0143],
         [ 0.1518, -0.2911,  0.1221,  0.5434],
         [ 0.9328,  0.2329, -0.6187,  0.3170],
         [ 0.6582,  0.1510,  0.6540, -0.6031]]])


In [8]:
torch.sum(M - I, dim=(1, 2))

tensor([5.2656, 3.5347, 2.5922])

In [13]:
flag = torch.sum(M - I, dim=(1, 2)) > 3

In [15]:
torch.mean(flag.float())

tensor(0.6667)

In [9]:
torch.sum(M[0] - I)

tensor(5.2656)