In [1]:
import torch

In [2]:
mask_params = torch.Tensor([1, 1, 2, 2,])

In [4]:
diff = torch.abs(mask_params.unsqueeze(0) - mask_params.unsqueeze(1))
print(diff)

tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.]])


In [9]:
mask = torch.exp(-diff)
print(mask)

tensor([[1.0000, 1.0000, 0.3679, 0.3679],
        [1.0000, 1.0000, 0.3679, 0.3679],
        [0.3679, 0.3679, 1.0000, 1.0000],
        [0.3679, 0.3679, 1.0000, 1.0000]])


In [10]:
from torch import Tensor
def get_laplacian(matrix:Tensor)->Tensor:
    assert matrix.ndim == 2 and matrix.shape[0] == matrix.shape[1]
    return torch.diag(torch.sum(matrix, dim=1)) - matrix

In [12]:
get_laplacian(mask)

tensor([[ 1.7358, -1.0000, -0.3679, -0.3679],
        [-1.0000,  1.7358, -0.3679, -0.3679],
        [-0.3679, -0.3679,  1.7358, -1.0000],
        [-0.3679, -0.3679, -1.0000,  1.7358]])

In [13]:
get_laplacian(mask) + mask

tensor([[2.7358, 0.0000, 0.0000, 0.0000],
        [0.0000, 2.7358, 0.0000, 0.0000],
        [0.0000, 0.0000, 2.7358, 0.0000],
        [0.0000, 0.0000, 0.0000, 2.7358]])